import { Vector3 } from 'three';

export interface CelestialBodyData {
  id: string;
  name: string;
  namePL: string;
  description: string;
  descriptionPL: string;
  type: 'star' | 'planet' | 'dwarf' | 'moon' | 'asteroid' | 'comet' | 'interstellar';
  radius: number; // Visual scale radius
  distance: number; // Distance from parent
  color: string; // Material color
  speed: number; // Orbital speed multiplier
  rotationSpeed: number;
  moons?: CelestialBodyData[];
  orbitColor?: string;
  ring?: { inner: number; outer: number; color: string; };
}

export const SOLAR_SYSTEM_DATA: CelestialBodyData[] = [
  {
    id: 'mercury',
    name: 'Mercury',
    namePL: 'Merkury',
    description: "The smallest planet in the Solar System and the closest to the Sun. It has no atmosphere to retain heat.",
    descriptionPL: "Najmniejsza planeta Układu Słonecznego i najbliższa Słońcu. Nie posiada atmosfery zatrzymującej ciepło.",
    type: 'planet',
    radius: 0.8,
    distance: 12,
    color: '#A5A5A5',
    speed: 4.1,
    rotationSpeed: 0.02,
    orbitColor: '#555',
  },
  {
    id: 'venus',
    name: 'Venus',
    namePL: 'Wenus',
    description: "The hottest planet due to a runaway greenhouse effect. Similar in size to Earth.",
    descriptionPL: "Najgorętsza planeta z powodu efektu cieplarnianego. Podobna wielkością do Ziemi.",
    type: 'planet',
    radius: 1.5,
    distance: 18,
    color: '#E3BB76',
    speed: 1.6,
    rotationSpeed: -0.01,
    orbitColor: '#766',
  },
  {
    id: 'earth',
    name: 'Earth',
    namePL: 'Ziemia',
    description: "Our home world, the only known planet to harbor life. 70% covered by water.",
    descriptionPL: "Nasz dom, jedyna znana planeta, na której istnieje życie. W 70% pokryta wodą.",
    type: 'planet',
    radius: 1.6,
    distance: 26,
    color: '#22A6B3',
    speed: 1.0,
    rotationSpeed: 0.05,
    orbitColor: '#357',
    moons: [
      {
        id: 'moon',
        name: 'Moon',
        namePL: 'Księżyc',
        description: "Earth's only natural satellite. Affects tides and stabilizes Earth's wobble.",
        descriptionPL: "Jedyny naturalny satelita Ziemi. Wpływa na pływy i stabilizuje ruch obrotowy Ziemi.",
        type: 'moon',
        radius: 0.4,
        distance: 3.5,
        color: '#DDDDDD',
        speed: 12.0,
        rotationSpeed: 0.01,
      }
    ]
  },
  {
    id: 'apophis',
    name: 'Apophis',
    namePL: 'Apophis',
    description: "A near-Earth asteroid that caused brief concern for a potential impact in 2029.",
    descriptionPL: "Planetoida bliska Ziemi, która wywołała obawy o potencjalne zderzenie w 2029 roku.",
    type: 'asteroid',
    radius: 0.2,
    distance: 24, // Near Earth
    color: '#555555',
    speed: 1.1,
    rotationSpeed: 0.1,
    orbitColor: '#333',
  },
  {
    id: 'bennu',
    name: 'Bennu',
    namePL: 'Bennu',
    description: "A carbon-rich asteroid, target of the OSIRIS-REx mission which collected samples.",
    descriptionPL: "Bogata w węgiel asteroida, cel misji OSIRIS-REx, która pobrała z niej próbki.",
    type: 'asteroid',
    radius: 0.2,
    distance: 28, // Near Earth
    color: '#333333',
    speed: 0.9,
    rotationSpeed: 0.1,
    orbitColor: '#333',
  },
  {
    id: 'mars',
    name: 'Mars',
    namePL: 'Mars',
    description: "The Red Planet, known for its iron oxide dust. Home to Olympus Mons, the largest volcano.",
    descriptionPL: "Czerwona Planeta, znana z pyłu tlenku żelaza. Dom Olympus Mons, największego wulkanu.",
    type: 'planet',
    radius: 1.1,
    distance: 34,
    color: '#EB4D4B',
    speed: 0.53,
    rotationSpeed: 0.04,
    orbitColor: '#733',
  },
  // Asteroid Belt Objects
  {
    id: 'vesta',
    name: 'Vesta',
    namePL: 'Westa',
    description: "One of the largest asteroids in the belt. It has a giant crater at its south pole.",
    descriptionPL: "Jedna z największych asteroid w pasie. Posiada ogromny krater na biegunie południowym.",
    type: 'asteroid',
    radius: 0.4,
    distance: 38,
    color: '#DCDCDC',
    speed: 0.45,
    rotationSpeed: 0.08,
    orbitColor: '#444',
  },
  {
    id: 'pallas',
    name: 'Pallas',
    namePL: 'Pallas',
    description: "The third-largest asteroid. Its orbit is highly inclined compared to other planets.",
    descriptionPL: "Trzecia co do wielkości asteroida. Jej orbita jest silnie nachylona względem innych planet.",
    type: 'asteroid',
    radius: 0.4,
    distance: 40,
    color: '#708090',
    speed: 0.44,
    rotationSpeed: 0.08,
    orbitColor: '#444',
  },
  {
    id: 'hygiea',
    name: 'Hygiea',
    namePL: 'Hygiea',
    description: "A major asteroid containing a large share of the mass of the asteroid belt.",
    descriptionPL: "Duża asteroida zawierająca znaczną część masy pasa planetoid.",
    type: 'asteroid',
    radius: 0.35,
    distance: 41,
    color: '#2F2F2F',
    speed: 0.43,
    rotationSpeed: 0.09,
    orbitColor: '#333',
  },
  {
    id: 'ceres',
    name: 'Ceres',
    namePL: 'Ceres',
    description: "The only dwarf planet in the inner solar system. It may have a subsurface ocean.",
    descriptionPL: "Jedyna planeta karłowata w wewnętrznym Układzie Słonecznym. Może posiadać podpowierzchniowy ocean.",
    type: 'dwarf',
    radius: 0.5,
    distance: 42,
    color: '#999999',
    speed: 0.4,
    rotationSpeed: 0.05,
    orbitColor: '#555',
  },
  {
    id: 'halley',
    name: "Halley's Comet",
    namePL: 'Kometa Halleya',
    description: "The most famous short-period comet, visible from Earth every 75-76 years.",
    descriptionPL: "Najsłynniejsza kometa krótkookresowa, widoczna z Ziemi co 75-76 lat.",
    type: 'comet',
    radius: 0.25,
    distance: 50, // Average/Visual position
    color: '#AEEEEE',
    speed: 0.2, // Highly variable in reality
    rotationSpeed: 0.1,
    orbitColor: '#87CEFA',
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    namePL: 'Jowisz',
    description: "The largest planet. A gas giant known for its Great Red Spot and many moons.",
    descriptionPL: "Największa planeta. Gazowy olbrzym znany z Wielkiej Czerwonej Plamy i wielu księżyców.",
    type: 'planet',
    radius: 4.5,
    distance: 60,
    color: '#F9CA24',
    speed: 0.08,
    rotationSpeed: 0.1,
    orbitColor: '#652',
    moons: [
      { id: 'io', name: 'Io', namePL: 'Io', description: "The most geologically active object in the Solar System.", descriptionPL: "Najbardziej aktywny geologicznie obiekt w Układzie Słonecznym.", type: 'moon', radius: 0.5, distance: 6, color: '#F8C291', speed: 8, rotationSpeed: 0.01 },
      { id: 'europa', name: 'Europa', namePL: 'Europa', description: "Has a smooth icy surface likely hiding a water ocean.", descriptionPL: "Ma gładką lodową powierzchnię, prawdopodobnie ukrywającą ocean wody.", type: 'moon', radius: 0.45, distance: 7.5, color: '#DFF9FB', speed: 6, rotationSpeed: 0.01 },
      { id: 'ganymede', name: 'Ganymede', namePL: 'Ganimedes', description: "The largest moon in the Solar System, bigger than Mercury.", descriptionPL: "Największy księżyc w Układzie Słonecznym, większy od Merkurego.", type: 'moon', radius: 0.6, distance: 9.5, color: '#95A5A6', speed: 4, rotationSpeed: 0.01 },
      { id: 'callisto', name: 'Callisto', namePL: 'Kallisto', description: "A heavily cratered moon with an ancient surface.", descriptionPL: "Mocno pokraterowany księżyc o bardzo starej powierzchni.", type: 'moon', radius: 0.58, distance: 11.5, color: '#5D4C46', speed: 3, rotationSpeed: 0.01 },
    ]
  },
  {
    id: 'saturn',
    name: 'Saturn',
    namePL: 'Saturn',
    description: "Famous for its extensive and complex ring system made of ice and rock.",
    descriptionPL: "Słynie z rozległego i złożonego systemu pierścieni wykonanych z lodu i skał.",
    type: 'planet',
    radius: 3.8,
    distance: 85,
    color: '#F0DF90',
    speed: 0.03,
    rotationSpeed: 0.09,
    orbitColor: '#654',
    ring: { inner: 4.5, outer: 7.5, color: '#C0A080' },
    moons: [
      { id: 'titan', name: 'Titan', namePL: 'Tytan', description: "The only moon with a thick atmosphere and liquid lakes.", descriptionPL: "Jedyny księżyc z gęstą atmosferą i płynnymi jeziorami.", type: 'moon', radius: 0.7, distance: 10, color: '#F39C12', speed: 3, rotationSpeed: 0.01 },
      { id: 'enceladus', name: 'Enceladus', namePL: 'Enceladus', description: "Shoots geysers of water ice from its south pole.", descriptionPL: "Wyrzuca gejzery lodu wodnego ze swojego bieguna południowego.", type: 'moon', radius: 0.3, distance: 6, color: '#FFFFFF', speed: 5, rotationSpeed: 0.01 },
    ]
  },
  {
    id: 'uranus',
    name: 'Uranus',
    namePL: 'Uran',
    description: "An ice giant that rotates on its side. It has a pale blue color from methane.",
    descriptionPL: "Lodowy olbrzym, który obraca się 'na boku'. Ma bladoniebieski kolor od metanu.",
    type: 'planet',
    radius: 2.5,
    distance: 110,
    color: '#7ED6DF',
    speed: 0.01,
    rotationSpeed: 0.06,
    orbitColor: '#256',
    moons: [
       { id: 'miranda', name: 'Miranda', namePL: 'Miranda', description: "Known for its chaotic and varied terrain.", descriptionPL: "Znana ze swojego chaotycznego i zróżnicowanego terenu.", type: 'moon', radius: 0.2, distance: 3.5, color: '#E0E0E0', speed: 6, rotationSpeed: 0.02 },
       { id: 'ariel', name: 'Ariel', namePL: 'Ariel', description: "The brightest and likely youngest surface of Uranus' moons.", descriptionPL: "Najjaśniejsza i prawdopodobnie najmłodsza powierzchnia księżyców Urana.", type: 'moon', radius: 0.3, distance: 4.5, color: '#D3D3D3', speed: 5, rotationSpeed: 0.02 },
       { id: 'umbriel', name: 'Umbriel', namePL: 'Umbriel', description: "The darkest of Uranus' major moons.", descriptionPL: "Najciemniejszy z głównych księżyców Urana.", type: 'moon', radius: 0.3, distance: 5.5, color: '#A9A9A9', speed: 4.5, rotationSpeed: 0.02 },
       { id: 'titania', name: 'Titania', namePL: 'Tytania', description: "The largest moon of Uranus.", descriptionPL: "Największy księżyc Urana.", type: 'moon', radius: 0.4, distance: 7.0, color: '#C0C0C0', speed: 3.5, rotationSpeed: 0.02 },
       { id: 'oberon', name: 'Oberon', namePL: 'Oberon', description: "The outermost major moon of Uranus.", descriptionPL: "Najdalszy główny księżyc Urana.", type: 'moon', radius: 0.38, distance: 8.5, color: '#B0B0B0', speed: 3, rotationSpeed: 0.02 },
    ]
  },
  {
    id: 'neptune',
    name: 'Neptune',
    namePL: 'Neptun',
    description: "The windiest planet, an ice giant deep blue in color.",
    descriptionPL: "Najbardziej wietrzna planeta, lodowy olbrzym o ciemnoniebieskiej barwie.",
    type: 'planet',
    radius: 2.4,
    distance: 130,
    color: '#30336B',
    speed: 0.006,
    rotationSpeed: 0.06,
    orbitColor: '#225',
    moons: [
      { id: 'triton', name: 'Triton', namePL: 'Tryton', description: "A large moon that orbits retrograde (backwards) relative to Neptune.", descriptionPL: "Duży księżyc, który orbituje wstecznie względem Neptuna.", type: 'moon', radius: 0.5, distance: 5, color: '#ECF0F1', speed: -2, rotationSpeed: 0.01 }, 
    ]
  },
  {
    id: 'pluto',
    name: 'Pluto',
    namePL: 'Pluton',
    description: "A dwarf planet in the Kuiper belt, once considered the 9th planet.",
    descriptionPL: "Planeta karłowata w pasie Kuipera, kiedyś uważana za 9. planetę.",
    type: 'dwarf',
    radius: 0.4,
    distance: 150,
    color: '#D1CCC0',
    speed: 0.004,
    rotationSpeed: 0.01,
    orbitColor: '#444',
  },
  {
    id: 'oumuamua',
    name: "'Oumuamua",
    namePL: "'Oumuamua",
    description: "The first known interstellar object detected passing through the Solar System.",
    descriptionPL: "Pierwszy znany obiekt międzygwiezdny wykryty podczas przelotu przez Układ Słoneczny.",
    type: 'interstellar',
    radius: 0.15,
    distance: 140, // Passing through
    color: '#8B0000',
    speed: 0.02,
    rotationSpeed: 0.5,
    orbitColor: '#800000',
  },
  {
    id: 'haumea',
    name: 'Haumea',
    namePL: 'Haumea',
    description: "A dwarf planet shaped like an egg due to its rapid rotation.",
    descriptionPL: "Planeta karłowata w kształcie jajka z powodu szybkiej rotacji.",
    type: 'dwarf',
    radius: 0.35, 
    distance: 160,
    color: '#BDC3C7',
    speed: 0.0035,
    rotationSpeed: 0.15,
    orbitColor: '#333',
  },
  {
    id: 'quaoar',
    name: 'Quaoar',
    namePL: 'Quaoar',
    description: "A large object in the Kuiper belt with a ring system.",
    descriptionPL: "Duży obiekt w pasie Kuipera posiadający system pierścieni.",
    type: 'dwarf',
    radius: 0.35,
    distance: 162,
    color: '#8B4513',
    speed: 0.0034,
    rotationSpeed: 0.02,
    orbitColor: '#333',
  },
  {
    id: 'varuna',
    name: 'Varuna',
    namePL: 'Waruna',
    description: "A large trans-Neptunian object named after a Vedic deity.",
    descriptionPL: "Duży obiekt transneptunowy nazwany na cześć bóstwa wedyjskiego.",
    type: 'dwarf',
    radius: 0.32,
    distance: 163,
    color: '#CD853F',
    speed: 0.0033,
    rotationSpeed: 0.04, // Fast rotator
    orbitColor: '#333',
  },
  {
    id: 'makemake',
    name: 'Makemake',
    namePL: 'Makemake',
    description: "One of the largest objects in the Kuiper belt, reddish in color.",
    descriptionPL: "Jeden z największych obiektów w pasie Kuipera, o czerwonawym kolorze.",
    type: 'dwarf',
    radius: 0.38,
    distance: 165,
    color: '#E67E22',
    speed: 0.0032,
    rotationSpeed: 0.02,
    orbitColor: '#333',
  },
  {
    id: 'salacia',
    name: 'Salacia',
    namePL: 'Salacia',
    description: "A large TNO with a very low albedo (surface brightness).",
    descriptionPL: "Duży obiekt transneptunowy o bardzo niskim albedo (jasności powierzchni).",
    type: 'dwarf',
    radius: 0.3,
    distance: 168,
    color: '#5F9EA0',
    speed: 0.0031,
    rotationSpeed: 0.02,
    orbitColor: '#333',
  },
  {
    id: 'eris',
    name: 'Eris',
    namePL: 'Eris',
    description: "Massive dwarf planet, similar size to Pluto but more massive.",
    descriptionPL: "Masywna planeta karłowata, podobna rozmiarem do Plutona, ale cięższa.",
    type: 'dwarf',
    radius: 0.4,
    distance: 170,
    color: '#FFFFFF',
    speed: 0.003,
    rotationSpeed: 0.01,
    orbitColor: '#333',
  },
  {
    id: 'orcus',
    name: 'Orcus',
    namePL: 'Orkus',
    description: "Often called 'anti-Pluto' because its orbit mirrors Pluto's.",
    descriptionPL: "Często nazywany 'anty-Plutonem', ponieważ jego orbita jest lustrzanym odbiciem Plutona.",
    type: 'dwarf',
    radius: 0.35,
    distance: 148, // Anti-Pluto, but placed further in list for render order
    color: '#778899',
    speed: 0.004,
    rotationSpeed: 0.02,
    orbitColor: '#444',
  },
  {
    id: 'gonggong',
    name: 'Gonggong',
    namePL: 'Gonggong',
    description: "A red dwarf planet with a highly eccentric orbit.",
    descriptionPL: "Czerwona planeta karłowata o bardzo wydłużonej orbicie.",
    type: 'dwarf',
    radius: 0.38,
    distance: 180,
    color: '#B22222',
    speed: 0.0025,
    rotationSpeed: 0.02,
    orbitColor: '#333',
  },
  {
    id: 'sedna',
    name: 'Sedna',
    namePL: 'Sedna',
    description: "A distant planetoid with an incredibly long orbital period (11,400 years).",
    descriptionPL: "Odległa planetoida o niezwykle długim okresie orbitalnym (11 400 lat).",
    type: 'dwarf',
    radius: 0.38,
    distance: 250, // Very far
    color: '#FF4500',
    speed: 0.001,
    rotationSpeed: 0.02,
    orbitColor: '#333',
  },
];

export const SUN_DATA = {
    name: 'Sun',
    namePL: 'Słońce',
    description: 'The star at the center of our Solar System. It provides light and energy for life on Earth.',
    descriptionPL: 'Gwiazda w centrum naszego Układu Słonecznego. Dostarcza światło i energię dla życia na Ziemi.'
}

export const GALAXY_DATA = {
    blackHoleRadius: 20,
    orbitRadius: 200,
    orbitSpeed: 0.5, // Visual speed
};

export const UI_TRANSLATIONS = {
  EN: {
    title: "Solar System 3D",
    subtitleDetailed: "Interactive Heliocentric Model",
    subtitleGalaxy: "Galactic Scale: Sagittarius A*",
    modeSolar: "Solar View",
    modeGalaxy: "Sagittarius A*",
    controls: "Controls",
    controlsList: [
      "LMB + Drag to Rotate",
      "RMB + Drag to Pan",
      "Scroll to Zoom"
    ],
    timeSim: "Time Simulation",
    resetCam: "Reset Camera",
    speed: "Speed",
    labels: "Labels",
    realTime: "Set Real-Time",
    realTimeActive: "Real-Time (J2000) Active"
  },
  PL: {
    title: "Układ Słoneczny 3D",
    subtitleDetailed: "Interaktywny Model Heliocentryczny",
    subtitleGalaxy: "Skala Galaktyczna: Sagittarius A*",
    modeSolar: "Widok Solarny",
    modeGalaxy: "Sagittarius A*",
    controls: "Sterowanie",
    controlsList: [
      "LPM + Przesuń by obracać",
      "PPM + Przesuń by przesuwać",
      "Scroll by przybliżać"
    ],
    timeSim: "Symulacja Czasu",
    resetCam: "Reset Kamery",
    speed: "Prędkość",
    labels: "Etykiety",
    realTime: "Tryb Rzeczywisty",
    realTimeActive: "Czas Rzeczywisty (J2000)"
  }
};
